FROM buildkite/puppeteer:latest

WORKDIR /src

COPY package*.json /src/

# Install Node packages 
RUN npm install --loglevel=error

# Copy the rest
COPY . .

# Test Frontend
RUN npm run test:coverage

# Build Frontend
RUN npm run build

