FROM squidex/dotnet:2.2-sdk-chromium-phantomjs-node

COPY package.json .

# Install Node packages 
RUN npm install

COPY . .

WORKDIR /

# Test Frontend
RUN npm test

# Build Frontend
RUN npm run build