/*
 * mydraft.cc
 *
 * @license
 * Copyright (c) Sebastian Stehle. All rights reserved.
*/

export const texts = {
    common: {
        about: 'About',
        advanced: 'Advanced',
        alignHorizontalCenter: 'Horizontal Center',
        alignHorizontalLeft: 'Horizontal Left',
        alignHorizontalRight: 'Horizontal Right',
        alignment: 'Alignment',
        alignVerticalBottom: 'Vertical Bottom',
        alignVerticalCenter: 'Vertical Center',
        alignVerticalTop: 'Vertical Top',
        apply: 'Apply',
        backgroundColor: 'Background Color',
        bringForwards: 'Bring Forwards',
        bringToFront: 'Bring to Front',
        copy: 'Copy',
        copyTooltip: 'Copy Items',
        custom: 'Custom',
        cut: 'Cut',
        cutTooltip: 'Cut Items',
        delete: 'Delete',
        deleteDiagramConfirm: 'Do you really want to delete the diagram?',
        diagram: 'Diagram',
        distributeHorizontally: 'Distribute Horizontally',
        distributeVertically: 'Distribute Vertically',
        findIcon: 'Find Icon',
        findPage: 'Find Page',
        findShape: 'Find Shape',
        fontSize: 'Font Size',
        foregroundColor: 'Foreground Color',
        group: 'Group',
        groupTooltip: 'Group Items',
        height: 'Height',
        icons: 'Icons',
        layout: 'Layout',
        link: 'Link',
        load: 'Load',
        loadingDiagramDone: 'Successfully loaded diagram.',
        loadingDiagramFailed: 'Failed to load diagram',
        lock: 'Lock',
        lockTooltip: 'Lock or unlock item',
        masterPage: 'Master Page',
        more: 'More',
        newDiagram: 'New',
        newDiagramTooltip: 'New Diagram',
        newVersion: 'A new version is available. Please press F5 to reload them.',
        none: 'None',
        noRecentDocument: 'No recent document found',
        openFromFile: 'Open from file',
        openFromFileTooltip: 'Open diagram from file',
        optionsTooltip: 'Show more options (CTRL + O)',
        ordering: 'Ordering',
        page: 'Page',
        pages: 'Pages',
        palette: 'Palette',
        paste: 'Paste',
        pasteTooltip: 'Paste Items',
        printDiagrams: 'Print Diagrams',
        printingStarted: 'Printing started...',
        recent: 'Recent',
        redo: 'Redo',
        remove: 'Delete',
        rename: 'Rename',
        removeTooltip: 'Delete selected items',
        saveDiagram: 'Save',
        saveDiagramToFile: 'Save to File',
        saveDiagramToFileTooltip: 'Save Diagram to File',
        saveDiagramTooltip: 'Save Diagram',
        savingDiagramDone: 'Diagram saved.',
        savingDiagramDoneUrl: (fullUrl: string) => `Diagram saved under ${fullUrl}.`,
        savingDiagramFailed: 'Failed t save diagram.', 
        sendBackwards: 'Send Backwards',
        sendToBack: 'Send to Back',
        shapes: 'Shapes',
        strokeColor: 'Stroke Color',
        strokeThickness: 'Stroke Thickness',
        textAlignment: 'Text Alignment',
        undo: 'Undo',
        ungroup: 'Ungroup',
        ungroupTooltip: 'Ungroup Items',
        unsaved: '(unsaved)',
        visual: 'Visual',
        width: 'Width',
        zoomIn: 'Zoom In',
        zoomOut: 'Zoom Out',
    },
};
