/*
 * mydraft.cc
 *
 * @license
 * Copyright (c) Sebastian Stehle. All rights reserved.
*/

export const texts = {
    common: {
        alignHorizontalCenter: 'Horizontal Center',
        alignHorizontalLeft: 'Horizontal Left',
        alignHorizontalRight: 'Horizontal Right',
        alignment: 'Alignment',
        alignVerticalBottom: 'Vertical Bottom',
        alignVerticalCenter: 'Vertical Center',
        alignVerticalTop: 'Vertical Top',
        backgroundColor: 'Background Color',
        bringForwards: 'Bring Forwards',
        bringToFront: 'Bring to Front',
        copy: 'Copy',
        copyTooltip: 'Copy Items',
        cut: 'Cut',
        cutTooltip: 'Cut Items',
        delete: 'Delete',
        deleteDiagramConfirm: 'Do you really want to delete the diagram?',
        distributeHorizontally: 'Distribute Horizontally',
        distributeVertically: 'Distribute Vertically',
        fontSize: 'Font Size',
        foregroundColor: 'Foreground Color',
        group: 'Group',
        groupTooltip: 'Group Items',
        link: 'Link',
        lock: 'Lock',
        lockTooltip: 'Lock or unlock item',
        masterPage: 'Master Page',
        none: 'None',
        ordering: 'Ordering',
        page: 'Page',
        paste: 'Paste',
        pasteTooltip: 'Paste Items',
        redo: 'Redo',
        remove: 'Delete',
        removeTooltip: 'Delete selected items',
        sendBackwards: 'Send Backwards',
        sendToBack: 'Send to Back',
        strokeColor: 'Stroke Color',
        strokeThickness: 'Stroke Thickness',
        textAlignment: 'Text Alignment',
        undo: 'Undo',
        ungroup: 'Ungroup',
        ungroupTooltip: 'Ungroup Items',
        zoomIn: 'Zoom IN',
        zoomOut: 'Zoom Out',
    },
};
