export const CommonTheme = {
    CONTROL_FONT_SIZE: 16,
    CONTROL_BACKGROUND_COLOR: 0xF0F0F0,
    CONTROL_BORDER_THICKNESS: 1,
    CONTROL_BORDER_COLOR: 0xc9c9c9,
    CONTROL_BORDER_RADIUS: 4,
    CONTROL_TEXT_COLOR: 0x252525
};